name: analyzer
on: [workflow_dispatch]
jobs:
  analyzer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - run: poetry install --no-interaction --no-root
      - run: poetry run python main.py -s src/analyzer.py -s src/io_utils.py -s tests/test1.py -s tests/test2.py
